fourWins <- NWins$new(n = 4L, k = 6L, l = 7L, verbose = T)
fourWins$makeMove(1, 4)
fourWins$makeMove(2, 4)
fourWins$makeMove(1, 4)
fourWins$makeMove(2, 4)
fourWins$makeMove(1, 4)
fourWins$makeMove(2, 4)
fourWins$makeMove(1, 4)
fourWins$makeMove(2, 4)
fourWins$clearBoard()
fourWins$makeMove(1, 4)
fourWins$makeMove(2, 3)
fourWins$makeMove(1, 3)
fourWins$makeMove(2, 4)
fourWins$makeMove(1, 4)
fourWins$makeMove(2, 2)
fourWins$makeMove(1, 3)
fourWins$makeMove(2, 3)
fourWins$makeMove(1, 6)
fourWins$makeMove(2, 4)
fourWins$makeMove(1, 5)
fourWins$makeMove(2, 7)
