source("source.R")
connectFour <- ConnectN$new(n = 4L, nrow = 6L, ncol = 7L, verbose = T)
connectFour$makeMove(1, 4)
connectFour$makeMove(1, 4)
connectFour$makeMove(1, 4)
connectFour$makeMove(1, 4)

connectFour$makeMove(1, 4)
connectFour$makeMove(2, 4)
connectFour$makeMove(1, 4)
connectFour$makeMove(2, 4)
connectFour$makeMove(1, 4)
connectFour$makeMove(2, 4)
connectFour$makeMove(1, 4)
connectFour$makeMove(2, 4)
connectFour$clearBoard()
connectFour$makeMove(1, 4)
connectFour$makeMove(2, 3)
connectFour$makeMove(1, 3)
connectFour$makeMove(2, 4)
connectFour$makeMove(1, 4)
connectFour$makeMove(2, 2)
connectFour$makeMove(1, 3)
connectFour$makeMove(2, 3)
connectFour$makeMove(1, 6)
connectFour$makeMove(2, 4)
connectFour$makeMove(1, 5)
connectFour$makeMove(2, 7)
connectFour$makeMove(1, 5)
connectFour$makeMove(2, 5)
connectFour$makeMove(1, 6)
connectFour$makeMove(2, 6)
connectFour$makeMove(1, 5)
connectFour$makeMove(2, 6)
connectFour$makeMove(1, 6)
connectFour$clearBoard()

connectFour$getValidMoves()
connectFour$makeMove(1, 1)
connectFour$makeMove(2, 1)
connectFour$makeMove(1, 1)
connectFour$makeMove(2, 1)
connectFour$makeMove(1, 1)
connectFour$makeMove(2, 1)
connectFour$getValidMoves()
